---
- name: Include common variables
  ansible.builtin.include_vars:
    file: "../vars/common.yml"
    name: "common_vars"

- name: Install required system dependencies for MySQL
  ansible.builtin.apt:
    name:
      - pkg-config
      - libmysqlclient-dev
      - python3-dev
      - build-essential
    state: present

- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install required Python MySQL modules
  ansible.builtin.pip:
    name:
      - mysqlclient
      - pymysql
    state: present

- name: Install mysql-server
  ansible.builtin.apt:
    name: mysql-server
    state: present
  notify: Start & Enable mysql service

- name: Ensure MySQL binds to all IP addresses
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = {{ common_vars.bind_address }}'
    state: present
  notify: Reload mysql

- name: Create database {{ common_vars.db_name }}
  community.mysql.mysql_db:
    login_unix_socket: "{{ common_vars.mysql_socket }}"
    name: "{{ common_vars.db_name }}"
    state: present

- name: Create MySQL user '{{ common_vars.db_user }}'
  community.mysql.mysql_user:
    login_unix_socket: "{{ common_vars.mysql_socket }}"
    name: "{{ common_vars.db_user }}"
    host: "{{ common_vars.db_host }}"
    password: "{{ common_vars.db_password }}"
    priv: "{{ common_vars.db_privileges }}"
    state: present
    column_case_sensitive: false
