---
- name: Start & enable apache2 service
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Reload apache2 service
  ansible.builtin.service:
    name: apache2
    state: reloaded
